#!/usr/bin/env bash

packages=( dotdeploy/desktop-fonts )

module_configure() {
    # Symlinks
    sudo ln -sfv /etc/fonts/conf.avail/11-lcdfilter-default.conf /etc/fonts/conf.d
    sudo ln -sfv /etc/fonts/conf.avail/10-sub-pixel-rgb.conf /etc/fonts/conf.d
    sudo ln -sfv /etc/fonts/conf.avail/10-hinting-slight.conf /etc/fonts/conf.d
    # sudo ln -sfv /etc/fonts/conf.avail/30-infinality-aliases.conf /etc/fonts/conf.d
}
