#!/usr/bin/env bash

case "$dd_distro" in
    gentoo)
        packages=( dotdeploy/editors-emacs )
        ;;
    ubuntu)
        packages=( dotdeploy-editors-emacs )
        ;;
esac

module_setup() {
    if [[ $dd_distro == "ubuntu" ]]; then
        dd::common::elevate_cmd add-apt-repository -y ppa:ubuntuhandbook1/emacs
        dd::common::elevate_cmd apt-get update
    fi
}

module_configure() {
    # Clone .emacs.d config
    dd::common::ensure_repo git@github.com:FrauH0lle/emacs.d.git ~/.emacs.d

    # Message
    MSG=$(cat <<-END
    Remember to install emacs via 'emacs-config deploy'.
END
       )
    dd::log::store_messages "editors/emacs" "$MSG"
}
