#!/usr/bin/env bash

case "$dd_distro" in
    gentoo)
        packages=( dotdeploy/dev-containers )
        ;;
    ubuntu)
        packages=( dotdeploy-dev-containers )
        ;;
esac

module_setup() {
    if [[ $dd_distro == "ubuntu" ]]; then
        dd::common::ensure_ppa michel-slm/distrobox
    fi
}

module_configure() {
    # Set subuid and subgid
    sudo touch /etc/subuid /etc/subgid
    sudo usermod --add-subuids 100000-165535 --add-subgids 100000-165535 "$USER"
    # Remove
    # sudo usermod --del-subuids 100000-165535 --del-subgids 100000-165535 $USER
}
